#runtime: nodejs16
#env: standard
#handlers:
#  - url: /(.*\..+)$
#    static_files: dist/\1
#    upload: dist/(.*\..+)$
#    secure: always
#    # catch all handler to index.html
#  - url: /.*
#    static_files: dist/index.html
#    upload: dist/index.html
#    secure: always
runtime: nodejs14
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_idle_instances: 0
  min_pending_latency: automatic
  max_idle_instances: 1
  max_pending_latency: automatic
handlers:
  - url: /.*
    redirect_http_response_code: 301
    script: auto
    secure: always